// examples/vue-turnstile/src/App.vue
<script setup lang="ts">
import { turnstile } from "@captigo/turnstile";
import type { CaptchaInstance, CaptchaToken } from "@captigo/vue";
import { ref } from "vue";

// ---------------------------------------------------------------------------
// Adapters — created once at the module level so the widget is not remounted
// on reactive updates.
// ---------------------------------------------------------------------------

// Managed: visible checkbox, fires automatically.
const managedAdapter = turnstile({
  siteKey: import.meta.env.VITE_TURNSTILE_SITE_KEY ?? "1x00000000000000000000AA",
  theme: "auto",
});

// Interactive (invisible): no visible widget; call execute() explicitly.
const invisibleAdapter = turnstile({
  siteKey: import.meta.env.VITE_TURNSTILE_SITE_KEY ?? "1x00000000000000000000AA",
  execution: "execute",
});

// ---------------------------------------------------------------------------
// Managed widget state
// ---------------------------------------------------------------------------

const managedToken = ref<CaptchaToken | null>(null);
const managedStatus = ref("Waiting…");

function onManagedSuccess(token: CaptchaToken) {
  managedToken.value = token;
  managedStatus.value = `Token received (${token.value.slice(0, 12)}…). Would send to server here.`;
}

function onManagedExpire() {
  managedToken.value = null;
  managedStatus.value = "Token expired. Please solve the challenge again.";
}

// ---------------------------------------------------------------------------
// Invisible widget state
// ---------------------------------------------------------------------------

const captchaRef = ref<CaptchaInstance>();
const invisibleStatus = ref("Click 'Submit' to trigger the challenge.");

async function handleInvisibleSubmit() {
  invisibleStatus.value = "Triggering challenge…";
  try {
    const inst = captchaRef.value;
    if (!inst) {
      invisibleStatus.value = "Captcha not ready.";
      return;
    }
    const token = await inst.execute("example-submit");
    invisibleStatus.value = `Token received (${token.value.slice(0, 12)}…). Would send to server here.`;
  } catch {
    invisibleStatus.value = "Challenge failed or was cancelled.";
  }
}
</script>

<template>
  <main style="font-family: system-ui; max-width: 600px; margin: 2rem auto; padding: 0 1rem">
    <h1>captigo — Vue 3 + Turnstile</h1>
    <p>
      This example uses the
      <a href="https://developers.cloudflare.com/turnstile/reference/testing/">
        Turnstile test site key
      </a>
      which always passes. Set <code>VITE_TURNSTILE_SITE_KEY</code> in
      <code>.env.local</code> to use a real key.
    </p>

    <!-- ── Managed widget ───────────────────────────────────────── -->
    <section>
      <h2>Managed widget (visible checkbox)</h2>
      <p>The challenge fires automatically when the user interacts with the widget.</p>

      <Captcha
        :adapter="managedAdapter"
        @success="onManagedSuccess"
        @expire="onManagedExpire"
        @error="(err) => (managedStatus = `Error: ${err.message}`)"
      />

      <p><strong>Status:</strong> {{ managedStatus }}</p>
      <p v-if="managedToken" style="font-family: monospace; font-size: 0.8rem; word-break: break-all">
        Token: {{ managedToken.value }}
      </p>
    </section>

    <hr />

    <!-- ── Invisible widget ──────────────────────────────────────── -->
    <section>
      <h2>Invisible widget (execute on submit)</h2>
      <p>No visible widget is rendered. The challenge fires when you click Submit.</p>

      <form @submit.prevent="handleInvisibleSubmit">
        <!-- Captcha renders an empty container; the adapter ignores its content -->
        <Captcha ref="captchaRef" :adapter="invisibleAdapter" />
        <button type="submit">Submit</button>
      </form>

      <p><strong>Status:</strong> {{ invisibleStatus }}</p>
    </section>
  </main>
</template>

// examples/react-turnstile/src/App.tsx
import { Captcha } from "@captigo/react";
import type { CaptchaHandle, CaptchaToken } from "@captigo/react";
import { turnstile } from "@captigo/turnstile";
import { useRef, useState } from "react";

// ---------------------------------------------------------------------------
// Adapters — created once outside the component so the widget isn't remounted
// on every render.
// ---------------------------------------------------------------------------

// Managed: renders a visible checkbox; challenge fires automatically.
const managedAdapter = turnstile({
  siteKey: import.meta.env.VITE_TURNSTILE_SITE_KEY ?? "1x00000000000000000000AA", // test key
  theme: "auto",
});

// Interactive (invisible): no visible widget; execute() must be called explicitly.
const invisibleAdapter = turnstile({
  siteKey: import.meta.env.VITE_TURNSTILE_SITE_KEY ?? "1x00000000000000000000AA",
  execution: "execute",
});

// ---------------------------------------------------------------------------
// Demo: managed widget
// ---------------------------------------------------------------------------

function ManagedExample() {
  const [token, setToken] = useState<CaptchaToken | null>(null);
  const [status, setStatus] = useState<string>("Waiting…");

  const handleSuccess = (t: CaptchaToken) => {
    setToken(t);
    setStatus(`Token received (${t.value.slice(0, 12)}…). Would send to server here.`);
  };

  const handleExpire = () => {
    setToken(null);
    setStatus("Token expired. Please solve the challenge again.");
  };

  return (
    <section>
      <h2>Managed widget (visible checkbox)</h2>
      <p>The challenge fires automatically when the user interacts with the widget.</p>

      <Captcha
        adapter={managedAdapter}
        onSuccess={handleSuccess}
        onExpire={handleExpire}
        onError={(err) => setStatus(`Error: ${err.message}`)}
      />

      <p>
        <strong>Status:</strong> {status}
      </p>

      {token && (
        <p
          style={{
            fontFamily: "monospace",
            fontSize: "0.8rem",
            wordBreak: "break-all",
          }}
        >
          Token: {token.value}
        </p>
      )}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Demo: invisible widget with imperative execute
// ---------------------------------------------------------------------------

function InvisibleExample() {
  const captchaRef = useRef<CaptchaHandle>(null);
  const [status, setStatus] = useState<string>("Click 'Submit' to trigger the challenge.");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus("Triggering challenge…");
    try {
      const widget = captchaRef.current;
      if (!widget) {
        setStatus("Captcha not ready.");
        return;
      }
      const token = await widget.execute("example-submit");
      setStatus(`Token received (${token.value.slice(0, 12)}…). Would send to server here.`);
    } catch {
      setStatus("Challenge failed or was cancelled.");
    }
  };

  return (
    <section>
      <h2>Invisible widget (execute on submit)</h2>
      <p>No visible widget is rendered. The challenge fires when you click Submit.</p>

      <form onSubmit={handleSubmit}>
        {/* The Captcha component renders an empty container — attach it anywhere */}
        <Captcha ref={captchaRef} adapter={invisibleAdapter} />
        <button type="submit">Submit</button>
      </form>

      <p>
        <strong>Status:</strong> {status}
      </p>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

export function App() {
  return (
    <main
      style={{
        fontFamily: "system-ui",
        maxWidth: 600,
        margin: "2rem auto",
        padding: "0 1rem",
      }}
    >
      <h1>captigo — React + Turnstile</h1>
      <p>
        This example uses the{" "}
        <a href="https://developers.cloudflare.com/turnstile/reference/testing/">
          Turnstile test site key
        </a>{" "}
        which always passes. Set <code>VITE_TURNSTILE_SITE_KEY</code> in <code>.env.local</code> to
        use a real key.
      </p>

      <ManagedExample />
      <hr />
      <InvisibleExample />
    </main>
  );
}
